version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: admin_panel_cc
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1333
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:1234@localhost:5432/admin_panel_cc
      SECRET_KEY: dev-secret-key
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 1440
      CORS_ORIGINS: http://localhost:3000,http://localhost:5173
      LOG_LEVEL: INFO
    depends_on:
      - db
volumes:
  postgres_data: