"""Add password_hash to Organization model

Revision ID: ba206a9d58cd
Revises: 36b80173f46b
Create Date: 2025-08-11 12:32:06.559272

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ba206a9d58cd'
down_revision = '36b80173f46b'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('password_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'password_hash')
    # ### end Alembic commands ###